# Generated by Django 5.0.1 on 2024-02-27 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_of_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
